### ISSUE TITLE
Add Breadcrums

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#253]
## Comportamento atteso

- Breadcrumb

@Clou-dia can you please add a screenshot?

## Comportamento attuale

- no breadcrumb

## Possibili soluzioni

@Clou-dia can you please add a screenshot?

**Comment by Clou-dia** [comment]
Home - no breadcrumb
Catalogo - home/catalogo
Asset - Home/Catalogo/nome dell’asset anche molto lungo
Home/L’iniziativa
Home/Domande frequenti
Home/Informativa privacy 
Home/Note legali

**Comment by Clou-dia** [comment]
Chiudo questa issue - risolviamo tramite PR https://github.com/teamdigitale/dati-semantic-frontend/pull/252
