### ISSUE TITLE
[FE] Home: Integrare img in hero space

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#255]
- [ ] img in hero space come da [figma](https://www.figma.com/file/1gMP1H6nemzoz74I23f5ig/National-Data-Catalogue_mvp_export?node-id=622%3A29809)

<img width="513" alt="Schermata 2022-11-03 alle 18 39 38" src="https://user-images.githubusercontent.com/98462345/199794983-e682a40c-8a4d-480e-8955-08aa0a939933.png">

img 
![Schema_img_home](https://user-images.githubusercontent.com/98462345/199795371-e5f8dc62-92ef-4445-8006-c8c919bd47b0.png)

**Comment by Clou-dia** [comment]
@ioggstream unica cosa non riesco ad assegnare a @DoomRock88 la issue, si può risolvere?

**Comment by ioggstream** [comment]
@Clou-dia chiedi a @mfortini  per aggiungere @DoomRock88 al team.

**Comment by Clou-dia** [comment]
<img width="928" alt="Schermata 2022-11-08 alle 17 19 46" src="https://user-images.githubusercontent.com/98462345/200619038-0eb09ebc-a09f-471f-a9aa-30d8b7c1ee98.png">

l'immagine non è visualizzata bene, rivedere ingombro

**Comment by Clou-dia** [comment]
da sistemare l'ingombro immagine

**Comment by Clou-dia** [comment]
verificato

**Comment by Clou-dia** [comment]
verificato
