### ISSUE TITLE
[v1] Menù - modificare voci menu/footer

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#260]
[ETICHETTE VOCI MENÙ PRIMO - NELL’ORDINE]
dx Catalogo --> porta al catalogo
sx L’iniziativa
sx Domande frequenti

[ETICHETTE FOOTER - NELL’ORDINE]
Note Legali
Informativa privacy --> modificare in italiano
Dichiarazione di Accessibilità --> accessibilità minuscolo 

la home del catalogo è raggiungibile al click su logo/titolo

rif. design su [figma](https://www.figma.com/file/1gMP1H6nemzoz74I23f5ig/National-Data-Catalogue_mvp_export?node-id=622%3A29809)

**Comment by DoomRock88** [comment]
![image](https://user-images.githubusercontent.com/52858167/199958143-0f3792c5-1229-486b-b12f-3df8317cbf42.png)

Ok ? se si sarà inserito nella prossima pr @Clou-dia

**Comment by DoomRock88** [comment]
![image](https://user-images.githubusercontent.com/52858167/199958708-185ca25b-0c03-44df-a777-269be47740e7.png)

come sopra @Clou-dia

**Comment by Clou-dia** [comment]
> ![image](https://user-images.githubusercontent.com/52858167/199958143-0f3792c5-1229-486b-b12f-3df8317cbf42.png)
> 
> Ok ? se si sarà inserito nella prossima pr @Clou-dia

<img width="394" alt="Schermata 2022-11-04 alle 12 23 28" src="https://user-images.githubusercontent.com/98462345/199961582-96d415cf-f07d-4173-8f1d-1b19d1bef465.png">
 credo serva più spazio tra header e breadcrumb almeno 30px di distanza

**Comment by Clou-dia** [comment]
> 
<img width="768" alt="Schermata 2022-11-04 alle 12 26 55" src="https://user-images.githubusercontent.com/98462345/199961942-bcfd5b55-715e-4a9f-9e2a-b7aeccb34316.png">


si, però in bianco, credo che l'hover sia invece nel colore che mostri tu

**Comment by DoomRock88** [comment]
fatto sarà nella prossima pr
