### ISSUE TITLE
[FE] Add a banner in index.html to advertise "under maintenance"

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#293]
## I Expect

- [x] a banner in index.html to advertise "under maintenance" or other information
- [x] the banner MUST be populated by an environment variable that can be set by ops team
- [x] the banner supports UTF-8 characters, e.g. "⚠️We are rolling out a new release!⚠️"
- [x] the banner MUST NOT support HTML tags or script, only text

@Clou-dia can you please sketch it?

## Notes

The banner will help us in managing the next rollouts, e.g. fixing https://github.com/teamdigitale/dati-semantic-backend/issues/44

**Comment by Clou-dia** [comment]
potrebbe essere questo 

![schema_sito in aggiornamento (2)](https://user-images.githubusercontent.com/98462345/201735938-61808454-8a28-4722-9959-e6cc9fa04831.jpg)

ne parlo con @DoomRock88 domani

**Comment by Clou-dia** [comment]
verificato
