### ISSUE TITLE
Infer keyClasses summary when missing

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#315]
## Comportamento atteso

When keyClass has an empty summary
```

{iri: "https://w3id.org/italia/onto/CPV/PersonTitle", summary: null}
```
I expect the FE to derive the summary from the associated asset.
The derived summary can be the asset name (e.g. `PersonTitle`) or its label/prefLabel retrieved from SparQL.

## Comportamento attuale

A list of blank nodes is displayed

![image](https://user-images.githubusercontent.com/1140844/203845728-2e8342d9-259f-4f9d-adb7-ab8c94c581a2.png)

cc: @Clou-dia 
see https://ndc-dev.apps.cloudpub.testedev.istat.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschema%2Fperson%2Fv202108.01%2FOAS3

**Comment by giorgialodi** [comment]
In essence we need to do the following during harvesting time:
