### ISSUE TITLE
[FE] favicon

### ISSUE THREAD

**Issue by mfortini** [teamdigitale/dati-semantic-frontend#323]
Favicon is currently DTD's icon
![immagine](https://user-images.githubusercontent.com/1104926/205047497-b4415784-dd15-48e0-aaa8-c1c96cf48f56.png)

It should be NDC's icon

**Comment by Clou-dia** [comment]
![favicon_schema](https://user-images.githubusercontent.com/98462345/205051679-d9e8c452-c2e6-442f-9047-9c0ef898bf3e.svg)


ecco qui

**Comment by Clou-dia** [comment]
<img width="37" alt="Schermata 2023-02-17 alle 15 02 06" src="https://user-images.githubusercontent.com/98462345/219676206-2822dac3-0492-4233-add4-c9b12e19601f.png">
è possibile avelo senza sfondo bianco?

**Comment by mfortini** [comment]
[favicon_package_v0.16.zip](https://github.com/teamdigitale/dati-semantic-frontend/files/10806744/favicon_package_v0.16.zip)
