### ISSUE TITLE
Link broken - Vocabolario Controllato dei Comuni d'Italia

### ISSUE THREAD

**Issue by AndreaTironi1** [teamdigitale/dati-semantic-frontend#370]
Non so se è il posto giusto ma non so dove altro scrivere.
Se vado sul 
Vocabolario Controllato dei Comuni d'Italia
e clicco su
https://w3id.org/italia/controlled-vocabulary/territorial-classifications/cities
ricevo
Oops! something went wrong
https://ontopia-virtuoso.agid.gov.it/sparql
connection refused
<https:​/​/​w3id.​org/​italia/​controlled-​vocabulary/​territorial-​classifications/​cities>

**Comment by giorgialodi** [comment]
Ciao @AndreaTironi1, il problema era dovuto al fatto che lo sparql endpoint di AGID, su cui insiste il visualizzatore HTML per i vocabolari controllati e ancora usato in questa fase da schema.gov.it, era giù. Al momento, il problema sembra risolto lato AGID e quindi ora il vocabolario è consultabile via LodView. Nelle prossime settimane sarà operativo il passaggio da SPARQL endpoint di AGID a SPARQL endpoint di schema.gov.it e tutti i visualizzatori saranno poi gestiti direttamente da schema. Grazie mille per la segnalazione. Se per te è ok, chiuderemmo l'issue :)

**Comment by AndreaTironi1** [comment]
grazie

**Comment by AndreaTironi1** [comment]
sisi chiudi pure rigrazie
