### ISSUE TITLE
Typo in the text of the home page

### ISSUE THREAD

**Issue by giorgialodi** [teamdigitale/dati-semantic-frontend#385]
## Comportamento attuale
serealizzazione (descrizione sezione Schemi Dati 

## Comportamento atteso
Correggere in "serializzazione"

**Comment by Clou-dia** [comment]
possiamo correggere anche questo typo

<img width="513" alt="Schermata 2023-08-04 alle 07 45 49" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/4f2fd829-ce9a-4a8a-9702-3dc00de6a289">

**Comment by Clou-dia** [comment]
Verificato, grazie
