### ISSUE TITLE
[FE] Eliminare link alla guida del catalogo

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#469]
Vista la revisione in corso della guida al catalogo eliminare i link che portano alla guida in particolare:

Il banner presente in home page:

- [x] Eliminare frase: Se vuoi contribuire al catalogo con un contenuto leggi la guida su docs italia 
- [x] Eliminare bottone e link: Scopri come contribuire

Applicare il banner come sopra descritto a tutte le pagine del catalogo:

- [x] Pagina ricerca
- [x] Pagine delle singole risorse semantiche
- [x] Pagina L'iniziativa
- [x] Pagina Domande frequenti
- [x] Pagina Informativa privacy

Desiderata

![Group 1585](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/d8bb402a-9b86-4e30-a3a1-b7c1b0e9aece)

**Comment by Francescopalermo** [comment]
@Clou-dia 
Modified the banner on the home page and in the Search Page, Pages for individual semantic resources, Initiative Page, Frequently Asked Questions Page, and Privacy Information Page.

**Comment by mauropratesi** [comment]
CC: @Clou-dia 

<img width="934" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/3e21ccf6-0957-4858-b064-b43afb08578d">


The tests were conducted using the Edge and Chrome browsers on a PC (Windows) in the TEST envoronment (https://ndc-test.apps.cloudpub.testedev.istat.it/), and indeed, the issues highlighted by the reported problem has been resolved. The screenshot refers to the PC device with the Edge browser, but the same result is also observed with the Chrome browser and with the following devices: iPad Mini, iPhone SE, Samsung Galaxy S20 Ultra, Samsung Galaxy S8+.
NOTE: In the case of these last devices, please check the possibility of having a single line for the phrase "Vai su github."
Tests on Safari and Brave browsers are yet to be conducted.
