### ISSUE TITLE
[FE] Change of icon in the footer of DTD

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#485]
Change the icon of DTD with the updated one, attaching it here as svg, png

![DTD_](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/35b8dcd4-14a5-41f1-863f-a3f2918be138)

![DTD](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/78449b8f-4666-41d7-a15f-2541352314cf)

**Comment by Francescopalermo** [comment]
#487 resolved the issue about the logo in .svg format.
@Clou-dia

**Comment by Clou-dia** [comment]
testing in "ndc-test"
adding this logo requires to delete the other logo of italian gov (stellone) 
<img width="217" alt="Schermata 2024-02-19 alle 11 40 47" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/a99dabab-3ceb-450a-b0d1-9ec11de2aade">

and the space between logo has changed with the new release. See https://padigitale2026.gov.it/ as correct reference of spacing
<img width="1395" alt="Schermata 2024-02-19 alle 11 39 44" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/ba9c54f3-b26e-4f58-a2de-ec077fea42ec">

**Comment by FrankMaverick** [comment]
@Clou-dia 
To understand each other better, should:

- we eliminate the logo of the Italian gov (stellone) and relative href ?
- we move everything to the left on a large screen ?


PS. should the gray bar remain before DTD logo?

**Comment by Clou-dia** [comment]
we eliminate the logo of the Italian gov (stellone) and relative href ? > Yes
we move everything to the left on a large screen ? > Yes
PS. should the gray bar remain before DTD logo? > no, can delete it

Thanks

**Comment by FrankMaverick** [comment]
@Clou-dia the footer has been updated as requested. Released in TEST environment.

**Comment by Clou-dia** [comment]
tested, ok
