### ISSUE TITLE
[FE] Tasto "Vai al sorgente" del vocabolario "Vocabolario Controllato Stati Civili" non funziona

### ISSUE THREAD

**Issue by mauropratesi** [teamdigitale/dati-semantic-frontend#491]
## Comportamento atteso
Cliccando sul tasto "Vai al sorgente" l'utente deve essere reindirizzato al repository relativo dell'asset semantico in [questione](https://www.schema.gov.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fcontrolled-vocabulary%2Fclassifications-for-people%2Fmarital-status-types).

## Comportamento attuale
Viene aperta una pagina di errore.
<img width="944" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/0cfbcc91-2fbf-4b03-84a5-76a2c9fc14df">

cc: @Clou-dia; @AgostinoPurificato 

Di seguito il [link ](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-people/marital-status-types)github del vocabolario controllato.

**Comment by ndc-dxc** [comment]
@mauropratesi si tratta di un errore del vocabolario, il quale non aveva la "distributionUrl" corretta. Tale issue è stata sistemata [qui](https://github.com/italia/daf-ontologie-vocabolari-controllati/commit/840429eb8b1fcfb0b5f6d3d3b305d695fb66de39#diff-b1d862a709ae7e65f35a9680aba5fea6546d360dd866f56274955b379372d36e)

Non sempre gli errori sono nel codice e sarebbe utile non aprire issue per gli sviluppatori a prescindere, poichè si sottraggono risorse utili dallo sviluppo per verificare issue relative ai dati.
In questo momento non ci sono troppi dati, ma quando saranno molti è plausibile pensare che qualcosa andrà male a causa dei file RDF. In tale scenario aprire una issue agli sviluppatori per verificare ogni singolo caso, senza scremare cosa può effettivamente dipendere da un bug e cosa invece da dati erronei, azzererebbe la capacità del team di sviluppo di progredire con gli sviluppi evolutivi.

@Clou-dia @giorgialodi FYI

**Comment by AgostinoPurificato** [comment]
Grazie per l'aggiornamento @ndc-dxc 

Purtroppo in alcuni casi, come questo, non è possibile dall'interfaccia del portale schema-gov.it capire a priori se un bug è relativo all'ui stessa o se nasce da un errore a livello dati. 

Siamo d'accordo sul fatto che serva una strategia diversa per potere indirizzare una issue verso il corretto repository/gruppo di lavoro, ma per farlo è in ogni caso necessaria una prima analisi che, lato nostro, non abbiamo gli strumenti per poter fare. 

Per tali motivi, cosa consigliate in casi come questo? Apriamo la issue assegnandola ad altra handle github e/o con label diversa?

Grazie.
CC: @Clou-dia @giorgialodi

**Comment by giorgialodi** [comment]
Sicuramente questo è un bug dei metadati del vocabolario e magari la prossima volta lo apriamo sul repo dove si trova il vocabolario. Detto questo, l'issue era stato aperto 2 settimane fa e penso abbiamo consentito a ISTAT di rilevare appunto un bug. Quel vocabolario è stato creato ed è gestito da ISTAT per conto del Ministero dell'Interno, quindi probabilmente questo è stato il canale più rapido da usare per comunicarlo.
Vedo più che altro dei metadati mancanti ma magari lo segnalo sull'altro repository.  Grazie a tutti.
