### ISSUE TITLE
[FE] Errori schema dati "Consultazione Adeguamento Per Ricongiunzione API"

### ISSUE THREAD

**Issue by mauropratesi** [teamdigitale/dati-semantic-frontend#492]
Sono stati individuati due errori [1) e 2)] riguardo il seguente [schema dati](https://www.schema.gov.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fpratica-ricongiuzione%2Flatest%2Fpratica-ricongiuzione.oas3.yaml) presente a Catalogo.
## Comportamento atteso
1) Cliccando sul tasto "Vai al sorgente" l'utente deve essere reindirizzato al repository dell'asset semantico.
2) L'utente, una volta che accede alla scheda dello schema dati, visualizza lo Swagger.

## Comportamento attuale
1) Viene aperta una pagina di errore.
<img width="947" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/f00136b8-d8c0-4da4-8be5-c4f7d0f0f3ef">

2) Viene mostrato il seguente errore.
<img width="629" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/7ac91f75-b89c-401e-98ba-ce57d5268e53">

Potreste verificare, in generale, **tutte** le altre risorse?

cc: @FrankMaverick; @Clou-dia; @AgostinoPurificato

**Comment by FrankMaverick** [comment]
Il problema è che nel TTL gli URL sono sbagliati (manca la 'N', ricongiuzione):
https://github.com/INPS-it/NDC/blob/d8f24804e82ddcd693edbb2adad53c07afa5c87b/assets/schemas/pratica-ricongiunzione/latest/index.ttl

```
dcat:accessURL <https://github.com/INPS-it/NDC/tree/main/assets/schemas/pratica-ricongiuzione/latest> ;
dcat:distribution <https://w3id.org/italia/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml> ;
dcat:downloadURL <https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml> ;
```

L'URL relativo a **dcat:accessURL** viene usato per il bottone "Vai al sorgente".
L'URL relativo a **downloadURL** viene usato per lo swagger.

Per cui, questo come altri casi analoghi, potranno essere risolti dall'organizzazione titolare del repository, lato Be o Fe non c'è nessun problema.

@Clou-dia @AgostinoPurificato @mauropratesi

**Comment by mauropratesi** [comment]
Buonasera, abbiamo aperto l'[issue](https://github.com/INPS-it/NDC/issues/1) direttamente nel repo sorgente di INPS.

@FrankMaverick; @Clou-dia; @AgostinoPurificato

**Comment by ndc-dxc** [comment]
@mauropratesi appurato che non sia un bug del frontend, quanto piuttosto un errore di pubblicazione, potresti cortesemente:

- togliere l'etichetta `bug`
- chiudere la issue

?

grazie per il supporto
