### ISSUE TITLE
[FE] Malfunzionamento breadcrumbs

### ISSUE THREAD

**Issue by mfortini** [teamdigitale/dati-semantic-frontend#494]
## Comportamento atteso

Premendo uno dei breadcrumb, dovrei ritornare alla pagina corrispondente, conservando lo stato in cui era

![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/1104926/aa5c1b87-3597-4891-be2f-dba446b35c47)

Per esempio premendo "catalogo"

## Comportamento attuale

* Sui browser Firefox-based, non si ha nessun effetto
* Sui browser Chrome-based, si ha l'effetto, ma è equivalente a premere il tasto "indietro" (ovvero se si arriva direttamente al link, si ottiene di tornare alla pagina precedente)

**Comment by Clou-dia** [comment]
@Francescopalermo

**Comment by VincenzoDeSisto** [comment]
@Clou-dia  The breadcrumb on the asset detail page has been fixed. The fix has been deployed to the test environment ([Schema - Test](https://ndc-test.apps.cloudpub.testedev.istat.it/)). We await your feedback. Thank you.

**Comment by Clou-dia** [comment]
verificato, da rilasciare in produzione al prossimo rilascio
