### ISSUE TITLE
[FE] Ricerca sul catalogo: select singola > select multipla

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#503]
Nell'attuale versione della ricerca le due select FILTRA PER STRUMENTO SEMANTICO e FILTRA PER CATEGORIA dovrebbero essere selezioni multiple, come avviene per la selezione da mobile.

<img width="1175" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/9bb28e4d-83b5-4221-8f99-2bee6260883b">

**Comment by FrankMaverick** [comment]
Di seguito alcune domande:

1. Il comportamento di tali filtri deve essere analogo al filtro Titolare, quindi con le checkbox all'interno della tendina, al netto della ricerca di autocompletamento?
2. Nel placeholder, quando non è selezionato nulla, lasciamo "scegli un'opzione" ?
3. Nel placeholder cosa va inserito in caso di selezione multipla?

@Clou-dia @AgostinoPurificato @VincenzoDeSisto

**Comment by steps88** [comment]
1. si
2. si
3. intendi una volta selezionate? l'ideale sarebbe scrivere il numero di selezioni fatte "3 elementi selezionati"

**Comment by FrankMaverick** [comment]
Attualmente, nella versione desktop, per il Filtro Titolare le opzioni selezionate vengono eliminate dalla tendina, mentre nella versione mobile rimangono nella tendina ma sono segnalate come selezionate.

1. Va bene così anche per i due filtri "strumento semantico" e "categoria" versione desktop?

2. E per il Titolare versione mobile?

**Comment by steps88** [comment]
Va bene così (1) anche per gli altri due filtri:
desktop spariscono dalla tendina e li vedo come chips, mobile rimangono selezionate le checkbox

**Comment by FrankMaverick** [comment]
Se l'utente ha selezionato tutte le opzioni nel filtro (es. degli strumenti semantici) e poi clicca sullo stesso filtro, questo dovrebbe:

- Mostrare tutti i risultati in modo che l'utente possa facilmente scegliere di nuovo tra le opzioni?
- Oppure, sarebbe meglio non mostrare nulla, poiché tutte le opzioni sono già selezionate?

Per il filtro del Titolare, attualmente in test, una volta selezionate tutte le opzioni, viene visualizzato "Nessun Risultato" se si prova a rifare la ricerca.

**Comment by steps88** [comment]
@FrankMaverick abbiamo razionalizzato i filtri con @Clou-dia, in modo da aver il minor numero di differenziazioni, e siamo arrivate alla conclusione che:
Tutti i filtri **mantengono** le selezioni all'interno della tendina, anche se esistono le chips all'esterno - così evitiamo il caso in cui si apre la tendina ma non c'è più nulla dentro.

Inoltre, dopo aver dato l'Ok e si riapre uno qualunque dei filtri, gli elementi selezionati sono i primi della lista, vedi img.
Lo stesso comportamento si rispecchia sul mobile.
<img width="989" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/85fab707-ae4e-433c-8f3d-4d9542e4a3e3">

Torna?

**Comment by VincenzoDeSisto** [comment]
La issue è stata rilasciata in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia @steps88 @AgostinoPurificato
