### ISSUE TITLE
[FE] Ricerca sul catalogo: stati di hover mancanti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#504]
Sul dropdown di ordinamento, la card, e le chips di ricerca mancano gli stati all'hover 

Dropdown > https://designers.italia.it/design-system/componenti/dropdown/
Card (speciale) > https://designers.italia.it/design-system/componenti/card/
Chips con x > https://italia.github.io/bootstrap-italia/docs/componenti/chips/#varianti-standard-e-grandi

<img width="208" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/a949f429-66ef-4c5b-af0c-38ea12e996f8">

![SCHEMA hover card](https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/ada8eda5-62b5-477d-8e58-8e02ed8aa472)
![SCHEMA hover chips](https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/10592d04-6e00-4860-acf0-97494df74b9a)

**Comment by FrankMaverick** [comment]
Di seguito alcune domande.

**Dropdown ordinamento**
Su Figma è stata prototipata una select, per la versione desktop, non una dropdown. Quindi è stato implementato come da prototipo. 

1. La dropdown è presente nella versione mobile, quindi si deve utilizzare quest'ultima versione?

**Card (speciale)**
Si suggerisce l'utilizzo della [card speciale](https://italia.github.io/bootstrap-italia/docs/componenti/card/#card-speciali), ma questa card diventa tutta cliccabile, per cui non sarebbe più possibile cliccare su URI.

2. Lo stato di hover sulla card deve essere inserito su tutta la card (come card speciale) o solo sul titolo dell'Asset?

**Chips con x**
L'hover può essere inserito, ma come da comportamento bootstrap, l'hover sulla chips non prevede l'icona di chiusura di colore blu (che invece è grigia) e lo sfondo della chips di colore bianco (che invece è trasparente).

3. Inseriamo l'hover con icona di chiusura grigia e sfondo trasparente come da bootstrap?

**Comment by VincenzoDeSisto** [comment]
La issue è stata rilasciata in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia @steps88 @AgostinoPurificato

**Comment by Clou-dia** [comment]
Testato sui i browser: Safari, Chrome, Edge, Firefox. 
Tutti ok al netto di Safari

**Comportamento attuale**
L'hover deve essere applicato solo agli elementi cliccabili (titolo, url), dal test anche gli elementi chips (tipologia risorsa e status stabile bozza) hanno stato hover, succede solo su Safari.

**Comportamento atteso** > Visto che le chips non sono cliccabili (ad oggi) non devono avere lo stato di hover


<img width="585" alt="Schermata 2024-05-02 alle 12 29 14" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/9de636e2-8bb7-44ea-a17c-a0f009a47bf3">
<img width="584" alt="Schermata 2024-05-02 alle 17 34 10" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/59e9a5ed-b759-49db-b333-7bc934f13c4d">

**Comment by VincenzoDeSisto** [comment]
@Clou-dia Non riusciamo a replicare il bug (screen in allegato). Potreste gentilmente descrivere passo dopo passo i passaggi per replicare la issue? Grazie in anticipo.

<img width="693" alt="image (1)" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/160047529/1f08b4be-65f6-45ee-a555-0a26ed09da8c">

**Comment by Clou-dia** [comment]
Provo con un video. Quando passo il mouse sugli elementi chips, vengono sottolineate.
Solo da Safari (provato da SO Big Sure e Monterey) 
https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/7b9e20f0-f572-443b-9b2d-182030968759

**Comment by Clou-dia** [comment]
non ancora verificata

**Comment by VincenzoDeSisto** [comment]
E' stata rilasciata la fix in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia

**Comment by Clou-dia** [comment]
RIfacendo il test da Safari lo vedo risolto in dev ma non in test
https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/cbca6e9f-dd5a-4fdd-b205-7deeda1092ed

**Comment by VincenzoDeSisto** [comment]
A causa di alcuni problemi nel flusso di rilascio, la modifica (presente in dev) non era stata propagata correttamente su test. La risoluzione adesso è presente anche sull'ambiente di test. Attendiamo vostro riscontro. Grazie

@Clou-dia
