### ISSUE TITLE
[FE] Ricerca sul catalogo: flusso dalla home

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#505]
Facendo ricerca dalla home, mi aspetto che la pagina del catalogo si apra e si posizioni con il focus a livello dei risultati. 
Ora scrolla verso l'alto

![SCHEMA ricerca home](https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/9aa5ac3e-d324-4690-926d-9d0b88af86a7)

**Comment by Clou-dia** [comment]
aggiungo a questa issue:

- [ ] Il componente di ricerca per parola chiave che si trova in home, dovrebbe essere allineato a quello che si trova nella pagina catalogo

<img width="1361" alt="Schermata 2024-04-10 alle 11 35 18" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/69418b4e-cba5-4b6e-bda6-39127ae38260">

**Comment by FrankMaverick** [comment]
Non è specificato, ma a questo punto lo scroll va fatto anche per i bottoni di selezione dell'Asset nella Home, che vanno a filtrare per strumento semantico in pagina "catalogo"?

@Clou-dia @AgostinoPurificato @VincenzoDeSisto

**Comment by Clou-dia** [comment]
si, grazie

**Comment by FrankMaverick** [comment]
Un piccolo dettaglio: la ricerca nella home, pur essendo identica a quella nel catalogo, avrà un effetto visivo differente a causa dello sfondo di colore diverso. Esempio di ricerca in home:

![Screenshot 2024-04-18 171402](https://github.com/teamdigitale/dati-semantic-frontend/assets/7274755/7c4d1a34-2ddf-47ca-b18e-d1d3ca842a50)

**Comment by VincenzoDeSisto** [comment]
La issue è stata rilasciata in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia @steps88 @AgostinoPurificato

**Comment by Clou-dia** [comment]
Verificato, da rilasciare nella prossima [Milestone Q1 2024](https://github.com/teamdigitale/dati-semantic-frontend/milestone/4)
