### ISSUE TITLE
[FE] Ricerca sul catalogo: ricerca per parola chiave su più parole

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#506]
dalla pagina di catalogo, quando inserisco una parola chiave nella barra di ricerca - cerco - e poi ne inserisco un'altra, la prima viene sovrascritta.
Mi aspetto che si vada ad aggiungere alla precedente 
cc @Clou-dia 

https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/fe4114e4-4563-44f8-8626-78ba439281a8

**Comment by Clou-dia** [comment]
chiudo perchè out of scope
