### ISSUE TITLE
[FE] Ricerca sul catologo: mobile > rimuovi filtri

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#507]
DA MOBILE
se tappo su Rimuovi tutti i filtri si richiude in automatico il pannello
Dovrebbe solo pulire la selezione

![SCHEMA rimuovi filtri mobile](https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/cf43abe6-0175-49e7-8369-6b7bd656f406)

**Comment by Clou-dia** [comment]
Preferire l'interazione come da questa issue, quindi il rimuovi filtri NON chiude la modale.

**Comment by FrankMaverick** [comment]
Quindi, il rimuove filtri non chiude la modale ma:

1.  pulisce solo i filtri nella modale, ma se viene chiusa la modale i filtri non saranno stati rimossi. Vengono rimossi solo cliccando su "Mostra risultati"

2. oppure, pulisce i filtri nella modale e li rimuove in background, senza la necessità di cliccare su "Mostra risultati"

@Clou-dia @AgostinoPurificato @VincenzoDeSisto

**Comment by Clou-dia** [comment]
L'interazione corretta è quella descritta nel punto 1 

> pulisce solo i filtri nella modale, ma se viene chiusa la modale i filtri non saranno stati rimossi. Vengono rimossi solo cliccando su "Mostra risultati"

**Comment by Clou-dia** [comment]
Verificato, da rilasciare nella prossima [Milestone Q1 2024](https://github.com/teamdigitale/dati-semantic-frontend/milestone/4)
