### ISSUE TITLE
[FE] Ricerca sul catologo: mobile > chips di ricerca non presenti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/dati-semantic-frontend#508]
DA MOBILE
Effettuata la ricerca non compaiono le chips delle parole.
Potrebbero comparire appena sotto i bottoni filtri e ordina @Clou-dia 

<img width="379" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/91465481/09feb91b-a53b-4ca7-bfc3-5c1a21e4feaa">

**Comment by Clou-dia** [comment]
Le chips sono solo per la ricerca testuale oppure anche per i filtri?

>  come per desktop

Dove devono essere inserite ?

> direi come per desktop sotto i bottoni filtri e ordinamento

In caso di testo molto lungo, devono andare a capo (quindi su n righe)?

> si

**Comment by FrankMaverick** [comment]
di seguito due versioni:

1. con le chips sotto i filtri:
![image (1)](https://github.com/teamdigitale/dati-semantic-frontend/assets/7274755/973f8524-0e50-45e9-9643-ae563dba6bd5)




2. con le chips sopra i filtri
 ![image (2)](https://github.com/teamdigitale/dati-semantic-frontend/assets/7274755/463bfb63-c800-4cf4-82df-b38a7c9abfd5)


Optiamo quindi per la versione 1.

In caso di testo molto lungo abbiamo preferito troncarlo (come per la categoria negli esempi), in quanto la chip di bootstrap italia non gestisce questo comportamento.

**Comment by steps88** [comment]
soluzione 1 mi torna. 
Ottimo per la troncatura dei lunghi.

**Comment by Clou-dia** [comment]
Verificato, da rilasciare nella prossima [Milestone Q1 2024](https://github.com/teamdigitale/dati-semantic-frontend/milestone/4)
