### ISSUE TITLE
[FE] Mobile - Margini pagine risorse semantiche / card home

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#509]
Mobile, per tutte le pagine foglia delle risorse semantiche
Applicare i margini alle pagine foglia così come sono stati applicati alla pagina catalogo per ampliare lo spazio di lettura delle card e metadati anche per breakpoint < di desktop.

Comportamento attuale

<img width="216" alt="Schermata 2024-04-10 alle 13 13 12" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/43d19438-7f70-4262-b624-d718c9823b9f">

<img width="215" alt="Schermata 2024-04-10 alle 13 13 01" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/e3bc41db-b8dd-4567-a88a-89b65be13f3b">

<img width="216" alt="Schermata 2024-04-10 alle 13 13 19" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/fbfd3966-7e5e-433f-9aed-69496fcfd997">

Comportamento atteso

<img width="215" alt="Schermata 2024-04-10 alle 13 12 48" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/34cc1a52-6ea9-4f09-874d-021820797bca">

**Comment by Clou-dia** [comment]
Anche in home, le card per categoria da mobile hanno lo stesso problema, applicare lo stesso margine.

<img width="217" alt="Schermata 2024-04-10 alle 13 18 02" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/efafe772-9087-4883-99ac-d827d7387efc">

**Comment by FrankMaverick** [comment]
All'interno della tabella nel dettaglio dell'Asset, bisogna ridurre i margini anche all'interno della tabella?
Esempio risultato:
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/7274755/e1a757aa-ea9f-4972-a643-b9ed3d9a5da4)

In generale, oltre a ridurre i margini esterni dei vari componenti, bisogna ridurre anche i margini all'interno dei componenti, dove possibile?

@Clou-dia @AgostinoPurificato @VincenzoDeSisto

**Comment by Clou-dia** [comment]
@FrankMaverick si se questo aiuta la leggibilità della tabella si

**Comment by VincenzoDeSisto** [comment]
La issue è stata rilasciata in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia @steps88 @AgostinoPurificato

**Comment by Clou-dia** [comment]
Verificato, da rilasciare nella prossima [Milestone Q1 2024](https://github.com/teamdigitale/dati-semantic-frontend/milestone/4)
