### ISSUE TITLE
[FE] - Componente dropdown da safari

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#510]
Il titolo del componente dropdown da safari risulta accorpato con la tendina
<img width="1259" alt="Schermata 2024-04-10 alle 11 28 29" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/a15bde06-9111-4392-a1bf-82239188fd60">

**Comment by FrankMaverick** [comment]
L'issue è stata risolta, come è possibile vedere nell'ambiente di test.

@Clou-dia @AgostinoPurificato

**Comment by Clou-dia** [comment]
Verificato, da rilasciare nella prossima [Milestone Q1 2024](https://github.com/teamdigitale/dati-semantic-frontend/milestone/4)
