### ISSUE TITLE
[FE] Modifica testi pag. Catalogo

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#526]
Pagina Catalogo - Modificare titolo e sottotitolo

**Cerca tra le risorse semantiche**
Cerca una o più risorse semantiche per parole chiave, filtrando i risultati per strumento semantico, titolare o categoria.

**Comment by Clou-dia** [comment]
@VincenzoDeSisto @Francescopalermo

**Comment by VincenzoDeSisto** [comment]
La issue è stata rilasciata in ambiente di [test](https://ndc-test.apps.cloudpub.testedev.istat.it/). Attendiamo un vostro riscontro. Grazie

@Clou-dia @steps88 @AgostinoPurificato
