### ISSUE TITLE
The viewport scrolls up to the top when changing page

### ISSUE THREAD

**Issue by bfabio** [teamdigitale/dati-semantic-frontend#533]
## Comportamento attuale

The viewport scrolls up with a slow animation when changing pages, which is disorienting and looks like the page didn't change at all:

https://github.com/teamdigitale/dati-semantic-frontend/assets/788293/3979976b-ddfa-4cc5-8fe0-814b52361444

**Comment by VincenzoDeSisto** [comment]
The issue has been released into [prod environment](https://schema.gov.it). We are waiting for your feedback to close the issue. Thanks

@bfabio @Clou-dia @ndc-istat

**Comment by bfabio** [comment]
Hi @VincenzoDeSisto 

It looks like the same behaviour is still there:

https://github.com/teamdigitale/dati-semantic-frontend/assets/788293/7a3e1ab5-4bc5-4aeb-9c98-fa5c55e9a55a

Additionally, the viewport scrolls with that animation also when going back and forward with the browsers' history.

**Comment by VincenzoDeSisto** [comment]
Hi, @bfabio 

The behavior you're describing was addressed 2 years ago in [this issue](https://github.com/teamdigitale/dati-semantic-frontend/issues/108). 
Could you please provide more details about the expected behavior?

@Clou-dia @ndc-istat

**Comment by bfabio** [comment]
Hello @VincenzoDeSisto,

this is about not scrolling the page when the user clicks a link that points to _another_ page . Note that the issue is not _positioning_ to a certain place on the target page, but rather performing that transition animation which makes it look like the target page is not a different page altogether.

This is the expected way (just an example, but any site will do):

https://github.com/teamdigitale/dati-semantic-frontend/assets/788293/4c197102-ea74-4692-9cc7-893d8a04a2ea

Clicking on "Scopri di più" instantly load the new page and positions the view at the begin. It doesn't _transition_ with a scrolling animation, as it does in the video of schema.gov.it.

**Comment by VincenzoDeSisto** [comment]
@bfabio We have released the changes to the test environment. We await your feedback to close the issue. Thanks.

**Comment by bfabio** [comment]
@VincenzoDeSisto the [test environment](https://ndc-dev.apps.cloudpub.testedev.istat.it/) works exactly as expected, thanks!

**Comment by Clou-dia** [comment]
Great, closing the issue, thanks
