### ISSUE TITLE
[FE] Inserire link alla guida al catalogo

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#562]
## Comportamento atteso
Nella Homepage, inserire il link alla guida al catalogo. https://teamdigitale.github.io/dati-semantic-guida-ndc-docs/index.html

Il link andrà al posto dell'attuale CTA "Scopri l'iniziativa" il testo del bottone sarà: "[Leggi la guida](https://teamdigitale.github.io/dati-semantic-guida-ndc-docs/index.html)" 

modificare la distanza tra i due bottoni "Esplora il catalogo" e "Leggi la guida" deve essere 20px

<img width="1218" alt="Schermata 2024-06-25 alle 16 42 55" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/8a8d2102-54e0-44f9-b92c-1315490199e4">

**Comment by VincenzoDeSisto** [comment]
@Clou-dia The changes have been released into the test environment. We are waiting for your tests and feedback. Thank you :)

CC: @ndc-istat

**Comment by Clou-dia** [comment]
tested, can be released thanks
